### ISSUE TITLE
Freihand metric

### ISSUE THREAD

**Issue by Dariushuangg** [zxz267/HaMuCo#3]
Hello there, thx for the very interesting work! I managed to reproduce your results using your metric, and I am trying to align your metric to the standard Freihand metric. I wonder where did you get `bbox_3d_size=0.4`? Thx

p.s. It'd be great if you can release the FreiHAND evaluation code mentioned in readme.

**Comment by zxz267** [comment]
> Hello there, thx for the very interesting work! I managed to reproduce your results using your metric, and I am trying to align your metric to the standard Freihand metric. I wonder where did you get `bbox_3d_size=0.4`? Thx
> 
> p.s. It'd be great if you can release the FreiHAND evaluation code mentioned in readme.

Thank you for your interest in our work. To the best of my recollection, "bbox_3d_size" is an empirical value derived from the coordinate range of the FreiHAND dataset, used for normalizing the coordinate values. I appreciate the reminder, and I will expedite the release of the FreiHAND evaluation code.

**Comment by Dariushuangg** [comment]
OK, thx!
