### ISSUE TITLE
Thank you for your reply and hard work!

### ISSUE THREAD

**Issue by qwer904** [zxz267/HaMuCo#4]
Thank you for your reply and hard work!
I have two more questions to ask you.
1.How can I input a picture and then display the hand skeleton? like in the paper.
2.Can the input be changed from a picture to real-time gesture recognition using a depth camera?

**Comment by zxz267** [comment]
> Thank you for your reply and hard work! I have two more questions to ask you. 1.How can I input a picture and then display the hand skeleton? like in the paper. 2.Can the input be changed from a picture to real-time gesture recognition using a depth camera?

1. You can structure the input image to match the format expected by the ["process_single_view_input" function](https://github.com/zxz267/HaMuCo/blob/7a6885bf122ff8ec5fca83663ffc46c09727b79b/models/base.py#L12). Subsequently, proceed to pass it through the model to obtain the output, which should then undergo processing via the ["process_output" function](https://github.com/zxz267/HaMuCo/blob/7a6885bf122ff8ec5fca83663ffc46c09727b79b/models/mvn.py#L329). Finally, utilize [this function]((https://github.com/zxz267/SAR/blob/2f229ac196fd72e605b9e5fbe6ab05f5bd87a027/utils/visualize.py#L16)) to display the 2D skeleton, utilizing the first two dimensions of the "output["coord_uvd"]" data.
2. I believe the input of HaMuCo could be altered to accommodate depth images by converting them into 3 channels. However, HaMuCo does not fully account for the nature of depth images, rendering it suboptimal for this input format and potentially necessitating further adjustments.
