### ISSUE TITLE
Visual demo

### ISSUE THREAD

**Issue by qwer904** [zxz267/HaMuCo#5]
Is there a demo with a hand skeleton that can be demonstrated using a real-time camera? If not, how should I write it?

**Comment by zxz267** [comment]
> Is there a demo with a hand skeleton that can be demonstrated using a real-time camera? If not, how should I write it?

No, there is no such demo currently available. You can obtain the camera images for model prediction, use [this code](https://github.com/zxz267/SAR/blob/main/utils/visualize.py) to visualize the hand skeleton, and then display the skeleton on your screen.
