### ISSUE TITLE
 Multi-view inference code and Pretrained model weight?

### ISSUE THREAD

**Issue by v-wewei** [zxz267/HaMuCo#6]
Dear author, would you like to release the code for inference and the pretrained model weight?

**Comment by zxz267** [comment]
> Dear author, would you like to release the code for inference and the pretrained model weight?

Unfortunately, there are no plans to update this repository in the near future. However, you can easily obtain the trained model using the training script. For multi-view inference, please refer to the paper and use triangulation to determine the hand center.

**Comment by v-wewei** [comment]
Thanks for your reply.
